name: Black and Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt --upgrade pip
    - name: Analysing the code-formatting with Black
      run: |
        black --check ./tests/
    - name: Analysing the code with PyLint
      run: |
        pylint $(git ls-files '*.py')
